[phases.setup]
nixPkgs = ['python311', 'postgresql']

[phases.install]
cmds = ['pip install -r backend/requirements.txt']

[phases.build]
cmds = ['cd backend && python manage.py collectstatic --noinput']

[start]
cmd = 'cd backend && python manage.py migrate && python manage.py create_default_admin && gunicorn core.wsgi:application --bind 0.0.0.0:$PORT --workers 3 --timeout 120'
